### ISSUE TITLE
Error:  java.lang.NoSuchMethodError: 'sbt.UpperStateOps sbt.package$.sbtStateToUpperStateOps(sbt.State)' error

### ISSUE THREAD

**Issue by atul-exabeam** [scalacenter/sbt-dependency-submission#105]
I get the following error when using 2.1.2 of the sbt-dependency-submission Github action 

Error:  java.lang.NoSuchMethodError: 'sbt.UpperStateOps sbt.package$.sbtStateToUpperStateOps(sbt.State)'

With 2.0.1, I was getting the  jawn.IncompleteParseException: exhausted input.

**Comment by adpi2** [comment]
Hey @atul-exabeam, thanks for the report. Which version of sbt do you use?

**Comment by atul-exabeam** [comment]
It is sbt v1.3.3

**Comment by adpi2** [comment]
Can you share the full stack trace of the error?

TBH I am not sure if I will be able to solve this issue. Meaning we won't support 1.3 anymore. Notice though that sbt 1.3 is EOL, it won't receive any bug fix or security patch from the sbt team. I recommend upgrading to the newer sbt 1.8.

**Comment by atul-exabeam** [comment]
There is not much else in terms of stack trace. Is there a way to specify sbt 1.8 when using the github action. 

Not sure if it helps but when the submission step begins it displays and uses sbt 1.3.3. I am guessing it the default version of sbt with the GH action runner that is running ubuntu

/usr/bin/sbt githubSubmitDependencyGraph {"ignoredModules":[],"ignoredConfigs":[],"onResolveFailure":"error"}
copying runtime jar...
[info] [launcher] getting org.scala-sbt sbt 1.3.3  (this may take some time)...
[info] [launcher] getting Scala 2.12.10 (for sbt)...

**Comment by atul-exabeam** [comment]
Never mind. Found where to set the sbt version. Works fine with 1.8.3
